# Generated by Django 3.0.6 on 2020-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name_p', models.CharField(max_length=80, verbose_name='Apellido paterno')),
                ('last_name_m', models.CharField(max_length=80, verbose_name='Apellido materno')),
                ('b_day', models.DateTimeField(blank=True, null=True)),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('curp', models.CharField(max_length=50, verbose_name='CURP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
    ]
