# Generated by Django 3.0.6 on 2020-05-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='b_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
