# Generated by Django 2.1.15 on 2020-06-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0003_auto_20200626_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('secure_number_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('secure_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Digita el número')),
                ('licence_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('licence', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ingresa licencia')),
                ('licence_started', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('licence_finished', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('psicofisico_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('recommendation_letter_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Operator_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_job', models.CharField(max_length=250, verbose_name='Ultimo trabajo')),
                ('period_started', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('period_finished', models.DateField(blank=True, null=True, verbose_name='Termino')),
                ('actual_job_where', models.CharField(blank=True, max_length=250, null=True, verbose_name='¿Dónde?')),
                ('actual_process_where', models.CharField(blank=True, max_length=250, null=True, verbose_name='¿Dónde?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Media', verbose_name='Medio')),
                ('id_mexa_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Mexa_interest', verbose_name='Interes')),
            ],
            options={
                'verbose_name': 'Información de operación',
                'verbose_name_plural': 'Informacion de operaciones',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name_p', models.CharField(max_length=80, verbose_name='Apellido paterno')),
                ('last_name_m', models.CharField(max_length=80, verbose_name='Apellido materno')),
                ('b_day', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('curp', models.CharField(max_length=50, verbose_name='CURP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Education_level', verbose_name='Grado academico')),
                ('id_marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Marital_status', verbose_name='Estado civil')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.State', verbose_name='Estado')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status', verbose_name='Status')),
                ('id_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Town', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_status_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_job', verbose_name='¿Está trabajando ahora?'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_status_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_process', verbose_name='¿Está llevando otro proceso?'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_truck_type',
            field=models.ManyToManyField(to='catalogues.Truck_type', verbose_name='Tipo de unidad'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador'),
        ),
    ]
