# Generated by Django 3.0.6 on 2020-05-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0003_media_mexa_interest_status_job_status_process_truck_type'),
        ('operators', '0002_auto_20200511_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Education_level', verbose_name='Grado academico')),
                ('id_marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Marital_status', verbose_name='Estado civil')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operators', verbose_name='Operador')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.State', verbose_name='Estado')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status', verbose_name='Status')),
                ('id_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Town', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Información general',
                'verbose_name_plural': 'Información general',
            },
        ),
        migrations.CreateModel(
            name='Last_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_job', models.CharField(max_length=250, verbose_name='Ultimo trabajo')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fishined_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de termino')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operators', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Ultimo trabajo',
                'verbose_name_plural': 'Ultimos trabajos',
            },
        ),
        migrations.CreateModel(
            name='Operator_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.General_information', verbose_name='Informacion G')),
                ('id_last_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Last_job', verbose_name='Ultimo trabajo')),
                ('id_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Media', verbose_name='Medio')),
                ('id_mexa_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Mexa_interest', verbose_name='Interes')),
                ('id_status_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_job', verbose_name='Estatus job')),
                ('id_status_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_process', verbose_name='Estatus process')),
                ('id_truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Truck_type', verbose_name='Tipo de unidad')),
            ],
            options={
                'verbose_name': 'Información de operador',
                'verbose_name_plural': 'Informacion de operador',
            },
        ),
        migrations.CreateModel(
            name='Actual_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_job', models.CharField(max_length=250, verbose_name='Trabajo actual')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operators', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Trabajo actual',
                'verbose_name_plural': 'Trabajos actuales',
            },
        ),
    ]
