# Generated by Django 2.1.15 on 2020-05-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_job', models.CharField(max_length=250, verbose_name='Trabajo actual')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
            ],
            options={
                'verbose_name': 'Trabajo actual',
                'verbose_name_plural': 'Trabajos actuales',
            },
        ),
        migrations.CreateModel(
            name='Last_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_job', models.CharField(max_length=250, verbose_name='Ultimo trabajo')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fishined_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de termino')),
            ],
            options={
                'verbose_name': 'Ultimo trabajo',
                'verbose_name_plural': 'Ultimos trabajos',
            },
        ),
        migrations.CreateModel(
            name='Operator_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_last_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Last_job', verbose_name='Ultimo trabajo')),
                ('id_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Media', verbose_name='Medio')),
                ('id_mexa_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Mexa_interest', verbose_name='Interes')),
            ],
            options={
                'verbose_name': 'Información de operador',
                'verbose_name_plural': 'Informacion de operador',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name_p', models.CharField(max_length=80, verbose_name='Apellido paterno')),
                ('last_name_m', models.CharField(max_length=80, verbose_name='Apellido materno')),
                ('b_day', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('curp', models.CharField(max_length=50, verbose_name='CURP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Education_level', verbose_name='Grado academico')),
                ('id_marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Marital_status', verbose_name='Estado civil')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.State', verbose_name='Estado')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status', verbose_name='Status')),
                ('id_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Town', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_status_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_job', verbose_name='Estatus job'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_status_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status_process', verbose_name='Estatus process'),
        ),
        migrations.AddField(
            model_name='operator_information',
            name='id_truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Truck_type', verbose_name='Tipo de unidad'),
        ),
        migrations.AddField(
            model_name='last_job',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='actual_job',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador'),
        ),
    ]
