# Generated by Django 3.0.6 on 2020-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator_information',
            name='actual_job_where',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='¿Dónde?'),
        ),
        migrations.AlterField(
            model_name='operator_information',
            name='actual_process_where',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='¿Dónde?'),
        ),
    ]
