# Generated by Django 2.1.15 on 2020-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator_information',
            name='period_finished',
            field=models.DateField(blank=True, null=True, verbose_name='Termino'),
        ),
        migrations.AlterField(
            model_name='operator_information',
            name='period_started',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
