# Generated by Django 3.0.6 on 2020-05-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20200514_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('secure_number_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('secure_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Digita el número')),
                ('licence_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('licence', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ingresa licencia')),
                ('licence_started', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('licence_finished', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento')),
                ('psicofisico_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('recommendation_letter_file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Operators', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentoss',
            },
        ),
    ]
