# Generated by Django 2.1.15 on 2020-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20200520_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='licence_finished',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='licence_started',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
