# Generated by Django 2.1.15 on 2020-06-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=55, verbose_name='Grado academico')),
            ],
            options={
                'verbose_name': 'Grado academico',
                'verbose_name_plural': 'Grados academicos',
            },
        ),
        migrations.CreateModel(
            name='Marital_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=30, verbose_name='Estado civil')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civil',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=55, verbose_name='Medio')),
            ],
            options={
                'verbose_name': 'Medio',
                'verbose_name_plural': 'Medios',
            },
        ),
        migrations.CreateModel(
            name='Mexa_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=250, verbose_name='Interes')),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Status_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_job', models.CharField(max_length=25, verbose_name='Status job')),
            ],
            options={
                'verbose_name': 'Status job',
                'verbose_name_plural': 'Status job',
            },
        ),
        migrations.CreateModel(
            name='Status_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_process', models.CharField(max_length=25, verbose_name='Status process')),
            ],
            options={
                'verbose_name': 'Status process',
                'verbose_name_plural': 'Status process',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Truck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=50, verbose_name='Tipo de tracto')),
            ],
            options={
                'verbose_name': 'Tipo de tracto',
                'verbose_name_plural': 'Tipos de tracto',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Status'),
        ),
    ]
