# Generated by Django 3.0.6 on 2020-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_education_level_marital_status_state_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=55, verbose_name='Medio')),
            ],
            options={
                'verbose_name': 'Medio',
                'verbose_name_plural': 'Medios',
            },
        ),
        migrations.CreateModel(
            name='Mexa_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=250, verbose_name='Interes')),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.CreateModel(
            name='Status_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_job', models.CharField(max_length=25, verbose_name='Status job')),
            ],
            options={
                'verbose_name': 'Status job',
                'verbose_name_plural': 'Status job',
            },
        ),
        migrations.CreateModel(
            name='Status_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_process', models.CharField(max_length=25, verbose_name='Status process')),
            ],
            options={
                'verbose_name': 'Status process',
                'verbose_name_plural': 'Status process',
            },
        ),
        migrations.CreateModel(
            name='Truck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=50, verbose_name='Tipo de tracto')),
            ],
            options={
                'verbose_name': 'Tipo de tracto',
                'verbose_name_plural': 'Tipos de tracto',
            },
        ),
    ]
