# Generated by Django 2.1.15 on 2020-06-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_auto_20200626_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
        migrations.RemoveField(
            model_name='town',
            name='status',
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='damn', max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='town_name',
            field=models.CharField(default='damin', max_length=50, verbose_name='Municipio'),
            preserve_default=False,
        ),
    ]
