# Generated by Django 2.1.15 on 2020-06-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_auto_20200626_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='id_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogues.State', verbose_name='Id de estado'),
            preserve_default=False,
        ),
    ]
